apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
  namespace: torrent
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 2000Gi
