apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: torrent
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.minh.pw`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8090