persistence:
  config:
    enabled: true
    existingClaim: config

  # media:
  #   enabled: true
  #   existingClaim: media
  #   mountPath: /media

  cache:
    enabled: true
    type: emptyDir
    mountPath: /cache
