apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 20Gi