apiVersion: v1
kind: Secret
metadata:
  name: bloodhound-secrets
  namespace: bloodhound
type: Opaque
stringData:
  POSTGRES_USER: bloodhound
  POSTGRES_PASSWORD: change-me-strong-postgres-password
  POSTGRES_DB: bloodhound

  NEO4J_USER: neo4j
  NEO4J_SECRET: change-me-strong-neo4j-password
