apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bloodhound-app
  namespace: bloodhound
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bloodhound.minh.pw`)
      kind: Rule
      services:
        - name: bloodhound-service
          port: 8080