apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-env
  namespace: vaultwarden
type: Opaque
stringData:
  WEBSOCKET_ENABLED: "true"
  DOMAIN: "https://vault.minh.pw"
  SIGNUPS_ALLOWED: "false"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_FROM: "nghgminh163.game@gmail.com"
  SMTP_USERNAME: "nghgminh163.game@gmail.com"
  SMTP_PASSWORD: "jxwp heft wrdm ilqi"

  PUSH_ENABLED: "true"
  PUSH_INSTALLATION_ID: "c469fdf4-348b-45e8-9652-b3a10108caa5"
  PUSH_INSTALLATION_KEY: "74lz7YwHybrCrehg6pDn"
