apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    # Web UI / API
    - match: Host(`vault.minh.pw`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80

    # WebSocket notifications
    - match: Host(`vault.minh.pw`) && PathPrefix(`/notifications/hub`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 3012
  tls: {}
