replicaCount: 1

# Đảm bảo resource/service tên đúng là "whoami" để IngressRoute gọi đúng service
fullnameOverride: "whoami"

image:
  repository: traefik/whoami
  tag: v1.11.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    http: 80

# Không dùng Ingress chuẩn
ingress:
  enabled: false

# Tạo IngressRoute (Traefik CRD) bằng extraDeploy
extraDeploy:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: whoami
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`whoami.minh.pw`)
          kind: Rule
          services:
            - name: whoami
              port: 80