apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ca-server
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ca.minh.pw`)
      kind: Rule
      services:
        - name: ca-server
          port: 80
