# Synology Services
apiVersion: v1
kind: Service
metadata:
  name: synology-dsm
  namespace: external-lb
spec:
  clusterIP: None
  ports:
    - name: https-dsm
      port: 5001
      targetPort: 5001
