# Synology Services
apiVersion: v1
kind: Service
metadata:
  name: synology-dsm
  namespace: external-lb
spec:
  clusterIP: None
  ports:
    - name: https-dsm
      port: 5001
      targetPort: 5001
---
# Adguard Services
apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: external-lb
spec:
  clusterIP: None
  ports:
    - name: adguard
      port: 3000
      targetPort: 3000
---
# Router Services
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: external-lb
spec:
  clusterIP: None
  ports:
    - name: router
      port: 80
      targetPort: 80