# Synology Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: synology-dsm
  namespace: external-lb
subsets:
  - addresses:
      - ip: 192.168.1.55
    ports:
      - name: https-dsm
        port: 5001
---
# Adguard Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard
  namespace: external-lb
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - name: adguard
        port: 3000
---
# Router Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: router
  namespace: external-lb
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - name: router
        port: 80
---
# VM Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: vm
  namespace: external-lb
subsets:
  - addresses:
      - ip: 192.168.1.86
    ports:
      - name: https-vm
        port: 443