apiVersion: v1
kind: Pod
metadata:
  name: ca-server
  namespace: kube-system
  labels:
    app: ca-server
spec:
  containers:
    - name: ca-server
      image: ca-server:latest
      imagePullPolicy: IfNotPresent
